name: Cross-Repository Orchestrator

on:
 workflow_dispatch:

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger python-app-speech-service
        env:
          GH_TOKEN: ${{ secrets.REPO_DISPATCH_PAT }}
        run: |
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer <YOUR_PAT>" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/sec-gh-account-hemanthreddy739/python-app-speech-service/dispatches -d '{"event_type":"run_build","client_payload":{"ref":"refs/heads/main"}}'
