name: Cross-Repository Orchestrator

on:
 workflow_dispatch:

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Python Repo 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh api --method POST -H "Accept: application/vnd.github.v3+json" /repos/sec-gh-account-hemanthreddy739/python-app-speech-service/dispatches -f event_type='run_build' -f client_payload='{"ref": "${{ github.ref }}"}'
